# Generated by Django 3.2.4 on 2021-11-05 12:30

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='/images/projects/default.jpg', null=True, upload_to=project.models.upload_),
        ),
    ]
