# Generated by Django 3.2.4 on 2021-11-05 14:29

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='/projects/default.jpg', null=True, upload_to=project.models.upload_),
        ),
    ]
